### ISSUE TITLE
Sum_node only works with  scipy version 0.19.0 or lower

### ISSUE THREAD

**Issue by asver12** [lumen-org/modelbase#55]
importing the SPNModel from mb_modelbase.models_core.spnmodel throws error with scipy version 1.3.0 or higher:

```
  File "/home/schm_li/.local/lib/python3.6/site-packages/mb_modelbase/models_core/spnmodel.py", line 18, in <module>
    from mb_modelbase.models_core.spn.spn import SPNParams, SPN
  File "/home/schm_li/.local/lib/python3.6/site-packages/mb_modelbase/models_core/spn/__init__.py", line 5, in <module>
    from mb_modelbase.models_core.spn.product_node import *
  File "/home/schm_li/.local/lib/python3.6/site-packages/mb_modelbase/models_core/spn/product_node.py", line 4, in <module>
    from .sum_node import SumNode
  File "/home/schm_li/.local/lib/python3.6/site-packages/mb_modelbase/models_core/spn/sum_node.py", line 2, in <module>
    from scipy.misc import logsumexp
ImportError: cannot import name 'logsumexp'
```

logsumexp was removed in [version 1.3.0 ](https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html?highlight=logsumexp)
